services:
  locust-master-web:
    image: locustio/locust:latest
    container_name: locust-master-web
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/locust
      - ./locust-reports:/reports
    working_dir: /locust
    command: -f locustfile.py --master -H http://host.docker.internal:8080 --web-port 8089
    extra_hosts:
      - "host.docker.internal:host-gateway"

  locust-worker-1:
    image: locustio/locust:latest
    container_name: locust-worker-1
    volumes:
      - ./locust:/locust
    working_dir: /locust
    command: -f locustfile.py --worker --master-host locust-master-web
    depends_on:
      - locust-master-web
    extra_hosts:
      - "host.docker.internal:host-gateway"

  locust-worker-2:
    image: locustio/locust:latest
    container_name: locust-worker-2
    volumes:
      - ./locust:/locust
    working_dir: /locust
    command: -f locustfile.py --worker --master-host locust-master-web
    depends_on:
      - locust-master-web
    extra_hosts:
      - "host.docker.internal:host-gateway"

  locust-headless:
    image: locustio/locust:latest
    container_name: locust-headless
    volumes:
      - ./locust:/locust
      - ./locust-reports:/reports
    working_dir: /locust
    command: -f locustfile.py --headless -u 50 -r 5 --run-time 2m --host=http://host.docker.internal:8080 --csv=/reports/headless
    extra_hosts:
      - "host.docker.internal:host-gateway"